mlc_config.json
Adding the patterns since markdown link checker was failing.
=> updating the mlc presets

README.md, docs/develop/apis/networks.md, docs/develop/apis/swagger.md, docs/develop/apis/tendermint-rpc.md, docs/develop/index.md, docs/develop/mainnet/api.md, docs/develop/testnet/auditing.md, docs/develop/tools/oracles.md, docs/protocol/evmos-cli/configuration.mdx, docs/protocol/evmos-cli/deterministic-builds.md, docs/protocol/evmos-cli/evmos-cli.md, docs/protocol/index.md, docs/use/key-management.md, docs/validate/mainnet.md, docs/validate/testnet.md, docusaurus.config.js
Small improvements to the develop and protocol sections.
=> docs (develop + protocol) improvements and linting

CONTRIBUTING.md, README.md, docs/develop/api/networks.mdx
Updated Contributing, a few networks endpoints, and the readme.
=> Contributing

docs/protocol/concepts/transactions.md
Related to https://linear.app/evmos/issue/DVREL-53/protocolconceptstransactions
=> chore(docs) add txs docs

src/pages/index.js
Updated home page link on dapp launches
=> link updates

docs/protocol/concepts/gas-and-fees.md, docusaurus.config.js
Adding algolia and broken link fixed
=> algolia and updated link issue

docs/develop/api/ethereum-json-rpc/index.md, docs/develop/api/ethereum-json-rpc/methods.md, docs/develop/build-a-dApp/build-smart-contracts/build-smart-contracts.md, docs/protocol/evmos-cli/configuration.mdx, docs/protocol/modules/erc20/index.md, docs/protocol/modules/evm/01_concepts.md, docs/protocol/modules/evm/02_state.md, docs/protocol/modules/evm/06_hooks.md, docs/protocol/modules/evm/09_client.md, docs/protocol/modules/feemarket/01_concepts.md, docs/protocol/modules/incentives/05_hooks.md, docs/protocol/modules/recovery/01_concepts.md, docs/protocol/modules/recovery/index.md, docs/protocol/modules/revenue/01_concepts.md, docs/protocol/modules/revenue/05_hooks.md, docs/validate/mainnet.md, docs/validate/setup-and-configuration/state-sync.md, docs/validate/testnet.md, docs/validate/upgrades/index.md, docs/validate/upgrades/manual-upgrades.md, docusaurus.config.js
Updated quite a few broken links that in the modules folder and other per mentioned issues.
=> broken links fixed and linting

docs/use/index.mdx
Change
> We believe that you shouldn't be constrained to interacting only with applications on one blockchain.
to
> We believe that you shouldn't be constrained to interacting ~only~ with applications on **only** one blockchain.
=> reposition wording of "only"

docs/develop/api/snapshots-archives.mdx, docs/protocol/concepts/accounts.md, docs/protocol/concepts/key-management.md, docs/protocol/concepts/keyring.md, docs/protocol/evmos-cli/configuration.mdx, docs/protocol/evmos-cli/multi-nodes.md, docs/protocol/evmos-cli/single-node.md, docs/protocol/index.md, docs/use/Interact-with-dApps/index.md, docs/use/connect-your-wallet/metamask.mdx, docs/validate/mainnet.md, docs/validate/relayers.md, docs/validate/security/index.md, docs/validate/setup-and-configuration/state-sync.md, docs/validate/testnet.md, docs/validate/upgrades/hard-fork-upgrades.md, docs/validate/upgrades/index.md
Fixed quite a bit of broken links pointed out by algolia.
=> Broken links

docs/develop/index.mdx, docs/develop/testnet/index.mdx, docs/protocol/concepts/signing.md, docs/protocol/concepts/tokens.md, docs/protocol/concepts/transactions.md, docs/use/connect-your-wallet/keplr.mdx, docs/use/connect-your-wallet/metamask.mdx, docs/use/faq.md, package-lock.json, package.json, src/utils/ChainConfig.js
- transaction docs expanded with EIP-712, txTypes, and overview
- updated a few dependencies
- added more areas for visibility on Testnet (Keplr and Metamask)
- better handling of errors with sweetalerts
=> expanded sections

docs/develop/smart-contracts/evm-extensions/distribution.md, docs/develop/smart-contracts/evm-extensions/evm-extensions.md, docs/develop/smart-contracts/evm-extensions/ibc-transfer.md, docs/develop/smart-contracts/list-evm-extensions.md
closes https://linear.app/evmos/issue/ENG-1306/ics20-precompile-docs
=> chore: add ICS-20 docs

docs/develop/smart-contracts/evm-extensions/evm-extensions.md, docs/develop/testnet/index.mdx
closes https://linear.app/evmos/issue/ENG-1782/update-academy-evm-extensions-article
=> chore: add links to academy article & workshop

docs/validate/setup-and-configuration/configuration.md
This PR adjusts the value of the `timout_commit` setting in the configuration docs.
----
Closes ENG-1830
=> chore: adjust timeout commit

src/css/custom.css, tailwind.config.js
Adds small style changes:
* increase left padding  for main content
* bigger h1 titles
=> impr(docs): add width padding and bigger font

docs/develop/tools/contract-verifications.md
Fix broken link to block explorer section
=> fix: block-explorers link

docs/protocol/evmos-cli/index.mdx
Add instructions to install the compiled binaries from the releases section
=> chore: update cli docs

docs/develop/smart-contracts/evm-extensions/authorization.md, docs/develop/smart-contracts/evm-extensions/distribution.md, docs/develop/smart-contracts/evm-extensions/evm-extensions.md, docs/develop/smart-contracts/evm-extensions/ibc-transfer.md, docs/develop/smart-contracts/evm-extensions/staking.md
=> chore: update evm extensions

docs/protocol/concepts/accounts.md
update Evnos to Evmos at Line 11
=> fix: update accounts.md for evmos mistake.

docs/protocol/modules/vesting.md
This PR updates the vesting module docs with the reworked user flow, which now includes a separation of the creation of a clawback vesting account from the funding.
=> imp(vesting): update vesting module docs

docs/validate/upgrades/list-of-upgrades.md
This PR updates the docs to reflect all recent software upgrades executed on-chain.
Closes [ENG-2069](https://linear.app/altiplanic/issue/ENG-2069/create-linear-ticket-template-for-release)
=> chore: adjust list of upgrades

docs/develop/api/snapshots-archives.mdx
=> adding galaxystaking.space

docs/protocol/metrics.md
closes https://linear.app/altiplanic/issue/ENG-2148/update-metrics-doc
=> chore: update metrics

docs/develop/api/networks.mdx
=> Remove deprecated Blockdaemon nodes

docs/develop/api/networks.mdx, docusaurus.config.js
Deleted unnecessary addresses.
=> Networks list update

docs/validate/upgrades/list-of-upgrades.md
This PR adds the `v15.0.0-rc1` upgrade to the list of testnet upgrades.
=> chore(upgrades): add v15.0.0-rc1 upgrade to testnet upgrades

docs/validate/upgrades/list-of-upgrades.md
This PR adjusts the list of upgrades to reflect the recent upgrades.
=> chore: update list of upgrades (v15)

docs/protocol/modules/vesting.md
This PR will update the documentation of the vesting module to reflect the new usage of the staking wrapper to perform delegation checks.
Closes: EVM-115
=> fix(vesting): Update vesting doc to v3
